### PR TITLE
Added ssl cert mount and emptyDir default for data

### PR DESCRIPTION
**Pull request by tvanderwal-lmco**
Here are the fixes I applied to the helm chart locally to address issues #79 and #80 in order to deploy them to our OpenShift clusters. Let me know if you like this implementation or would like me to change anything.

### CODE REVIEW

**Comment by tvanderwal-lmco** [comment]
@ozkatz Hey Oz, I forgot all about these changes and it looks like I need someone to approve it before the pipeline runs again.  It originally broke because there was no default ssl section but now it should be good to go

**Comment by ozkatz** [comment]
@johnnyaug can you help getting this one merged?

**Comment by johnnyaug** [comment]
Hey @tvanderwal-lmco, thank you for your effort and sorry for the delay, I missed this PR.

I would like to suggest solving this by introducing new properties `extraVolumes` and `extraVolumeMounts`, which will allow the deployer to define and mount any volumes. [Here](https://github.com/bitnami/charts/blob/master/bitnami/nginx/templates/deployment.yaml) is a reference from the nginx bitnami chart.

WDYT?

**Comment by tvanderwal-lmco** [comment]
@johnnyaug Thanks I will take a look! After a quick look at that example I think the one thing that might be an issue is doing and empty-dir mount on `/etc/ssl/certs` when the `extraVolumes` isn't set which would clear out the defaults from the container. Would that be an issue?

**Comment by johnnyaug** [comment]
@tvanderwal-lmco, the way I see it, you wouldn't specify the mount for `/etc/ssl/certs` in `extraVolumeMounts` unless you also set `extraVolumes`. This way, no mount happens unless you explicitly specify it. Does that make sense?

**Comment by tvanderwal-lmco** [comment]
@johnnyaug Sorry I went back into the example and realized I misread what was happening. That should work fine and I'll work that this week! Thanks for the feedback

**Comment by tvanderwal-lmco** [comment]
@johnnyaug found some extra time and was able to test out those changes. Feel free to take another look when you have a free minute!

**Review by johnnyaug — APPROVED** [review]
Looking great, thank you!

**Comment by tvanderwal-lmco** [comment]
@johnnyaug Looks like the pipeline failed since I didn't update the version. I pulled the remote master and bumped it. Let me know if there is anything else I need to update!

**Pull request merged**
